server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://findu-api-uwii3tfcqa-ue.a.run.app/;
        proxy_set_header Host findu-api-uwii3tfcqa-ue.a.run.app;
        proxy_set_header Authorization $http_authorization;
    }
}
