"""add statement_month and payment_due_date to transactions

Revision ID: 411bfd1d9b34
Revises: 90b771111bf2
Create Date: 2026-04-28 17:53:22.858488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '411bfd1d9b34'
down_revision: Union[str, Sequence[str], None] = '90b771111bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'account_type',
               existing_type=postgresql.ENUM('CHECKING', 'SAVINGS', 'CREDIT_CARD', name='accounttypeenum'),
               nullable=False)
    op.add_column('transactions', sa.Column('statement_month', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_due_date')
    op.drop_column('transactions', 'statement_month')
    op.alter_column('accounts', 'account_type',
               existing_type=postgresql.ENUM('CHECKING', 'SAVINGS', 'CREDIT_CARD', name='accounttypeenum'),
               nullable=True)
    # ### end Alembic commands ###
