"""add import_batch_id to transactions

Revision ID: 855bd75f8a67
Revises: 411bfd1d9b34
Create Date: 2026-05-21 15:44:20.801193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855bd75f8a67'
down_revision: Union[str, Sequence[str], None] = '411bfd1d9b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('import_batch_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'import_batch_id')
    # ### end Alembic commands ###
