"""add valid_until to recurring_expenses

Revision ID: c3377e33eab6
Revises: da4ca9600821
Create Date: 2026-05-27 17:40:50.534454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3377e33eab6'
down_revision: Union[str, Sequence[str], None] = 'da4ca9600821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_expenses', sa.Column('valid_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_expenses', 'valid_until')
    # ### end Alembic commands ###
